name: brett-buskirk-dev
region: nyc
domains:
- domain: brett-buskirk.dev
  type: PRIMARY
- domain: www.brett-buskirk.dev
  type: ALIAS
ingress:
  rules:
  - component:
      name: site
    match:
      path:
        prefix: /
static_sites:
- build_command: npm run build
  catchall_document: index.html
  environment_slug: node-js
  envs:
  - key: NODE_VERSION
    scope: BUILD_TIME
    value: "22"
  github:
    branch: main
    deploy_on_push: true
    repo: brett-buskirk/brett-buskirk-dev
  name: site
  output_dir: dist
